# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

setdata_03_lmm_CM <- function(y1, t1, Ti1, fTi1, cluster_start1, cluster_end1, y0, t0, Ti_til0, cluster_start0, cluster_end0) {
    .Call(`_longscreenfun_setdata_03_lmm_CM`, y1, t1, Ti1, fTi1, cluster_start1, cluster_end1, y0, t0, Ti_til0, cluster_start0, cluster_end0)
}

setquad_03_lmm_CM <- function(Ti_mat, lw_mat, fTi_mat, Ti_til0) {
    .Call(`_longscreenfun_setquad_03_lmm_CM`, Ti_mat, lw_mat, fTi_mat, Ti_til0)
}

cluster_ll_cpp <- function(r, sigma_b, sigma) {
    .Call(`_longscreenfun_cluster_ll_cpp`, r, sigma_b, sigma)
}

observed_cluster_ll_cpp <- function(data_ptr_sexp, theta_in) {
    .Call(`_longscreenfun_observed_cluster_ll_cpp`, data_ptr_sexp, theta_in)
}

missing_cluster_ll_cpp <- function(data_ptr_sexp, quad_ptr_sexp, theta_in) {
    .Call(`_longscreenfun_missing_cluster_ll_cpp`, data_ptr_sexp, quad_ptr_sexp, theta_in)
}

ll_R_cpp <- function(theta_in, data_ptr_sexp, quad_ptr_sexp) {
    .Call(`_longscreenfun_ll_R_cpp`, theta_in, data_ptr_sexp, quad_ptr_sexp)
}

ll_R_cpp_vec <- function(theta_in, data_ptr_sexp, quad_ptr_sexp) {
    .Call(`_longscreenfun_ll_R_cpp_vec`, theta_in, data_ptr_sexp, quad_ptr_sexp)
}

