// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// setdata_03_lmm_CM
SEXP setdata_03_lmm_CM(const Eigen::Map<Eigen::VectorXd> y1, const Eigen::Map<Eigen::VectorXd> t1, const Eigen::Map<Eigen::VectorXd> Ti1, const Eigen::Map<Eigen::VectorXd> fTi1, const Rcpp::IntegerVector cluster_start1, const Rcpp::IntegerVector cluster_end1, const Eigen::Map<Eigen::VectorXd> y0, const Eigen::Map<Eigen::VectorXd> t0, const Eigen::Map<Eigen::VectorXd> Ti_til0, const Rcpp::IntegerVector cluster_start0, const Rcpp::IntegerVector cluster_end0);
RcppExport SEXP _longscreenfun_setdata_03_lmm_CM(SEXP y1SEXP, SEXP t1SEXP, SEXP Ti1SEXP, SEXP fTi1SEXP, SEXP cluster_start1SEXP, SEXP cluster_end1SEXP, SEXP y0SEXP, SEXP t0SEXP, SEXP Ti_til0SEXP, SEXP cluster_start0SEXP, SEXP cluster_end0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type Ti1(Ti1SEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type fTi1(fTi1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector >::type cluster_start1(cluster_start1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector >::type cluster_end1(cluster_end1SEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type y0(y0SEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type t0(t0SEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type Ti_til0(Ti_til0SEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector >::type cluster_start0(cluster_start0SEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector >::type cluster_end0(cluster_end0SEXP);
    rcpp_result_gen = Rcpp::wrap(setdata_03_lmm_CM(y1, t1, Ti1, fTi1, cluster_start1, cluster_end1, y0, t0, Ti_til0, cluster_start0, cluster_end0));
    return rcpp_result_gen;
END_RCPP
}
// setquad_03_lmm_CM
SEXP setquad_03_lmm_CM(const Eigen::Map<Eigen::MatrixXd> Ti_mat, const Eigen::Map<Eigen::MatrixXd> lw_mat, const Eigen::Map<Eigen::MatrixXd> fTi_mat, const Eigen::Map<Eigen::VectorXd> Ti_til0);
RcppExport SEXP _longscreenfun_setquad_03_lmm_CM(SEXP Ti_matSEXP, SEXP lw_matSEXP, SEXP fTi_matSEXP, SEXP Ti_til0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type Ti_mat(Ti_matSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type lw_mat(lw_matSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type fTi_mat(fTi_matSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type Ti_til0(Ti_til0SEXP);
    rcpp_result_gen = Rcpp::wrap(setquad_03_lmm_CM(Ti_mat, lw_mat, fTi_mat, Ti_til0));
    return rcpp_result_gen;
END_RCPP
}
// cluster_ll_cpp
double cluster_ll_cpp(const Eigen::Map<Eigen::VectorXd> r, const double sigma_b, const double sigma);
RcppExport SEXP _longscreenfun_cluster_ll_cpp(SEXP rSEXP, SEXP sigma_bSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type r(rSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma_b(sigma_bSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(cluster_ll_cpp(r, sigma_b, sigma));
    return rcpp_result_gen;
END_RCPP
}
// observed_cluster_ll_cpp
Eigen::VectorXd observed_cluster_ll_cpp(SEXP data_ptr_sexp, const Eigen::Map<Eigen::VectorXd> theta_in);
RcppExport SEXP _longscreenfun_observed_cluster_ll_cpp(SEXP data_ptr_sexpSEXP, SEXP theta_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type data_ptr_sexp(data_ptr_sexpSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type theta_in(theta_inSEXP);
    rcpp_result_gen = Rcpp::wrap(observed_cluster_ll_cpp(data_ptr_sexp, theta_in));
    return rcpp_result_gen;
END_RCPP
}
// missing_cluster_ll_cpp
Eigen::VectorXd missing_cluster_ll_cpp(SEXP data_ptr_sexp, SEXP quad_ptr_sexp, const Eigen::Map<Eigen::VectorXd> theta_in);
RcppExport SEXP _longscreenfun_missing_cluster_ll_cpp(SEXP data_ptr_sexpSEXP, SEXP quad_ptr_sexpSEXP, SEXP theta_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type data_ptr_sexp(data_ptr_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type quad_ptr_sexp(quad_ptr_sexpSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type theta_in(theta_inSEXP);
    rcpp_result_gen = Rcpp::wrap(missing_cluster_ll_cpp(data_ptr_sexp, quad_ptr_sexp, theta_in));
    return rcpp_result_gen;
END_RCPP
}
// ll_R_cpp
Rcpp::List ll_R_cpp(const Eigen::Map<Eigen::VectorXd> theta_in, SEXP data_ptr_sexp, SEXP quad_ptr_sexp);
RcppExport SEXP _longscreenfun_ll_R_cpp(SEXP theta_inSEXP, SEXP data_ptr_sexpSEXP, SEXP quad_ptr_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type theta_in(theta_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type data_ptr_sexp(data_ptr_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type quad_ptr_sexp(quad_ptr_sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(ll_R_cpp(theta_in, data_ptr_sexp, quad_ptr_sexp));
    return rcpp_result_gen;
END_RCPP
}
// ll_R_cpp_vec
Eigen::VectorXd ll_R_cpp_vec(const Eigen::Map<Eigen::VectorXd> theta_in, SEXP data_ptr_sexp, SEXP quad_ptr_sexp);
RcppExport SEXP _longscreenfun_ll_R_cpp_vec(SEXP theta_inSEXP, SEXP data_ptr_sexpSEXP, SEXP quad_ptr_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type theta_in(theta_inSEXP);
    Rcpp::traits::input_parameter< SEXP >::type data_ptr_sexp(data_ptr_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type quad_ptr_sexp(quad_ptr_sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(ll_R_cpp_vec(theta_in, data_ptr_sexp, quad_ptr_sexp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_longscreenfun_setdata_03_lmm_CM", (DL_FUNC) &_longscreenfun_setdata_03_lmm_CM, 11},
    {"_longscreenfun_setquad_03_lmm_CM", (DL_FUNC) &_longscreenfun_setquad_03_lmm_CM, 4},
    {"_longscreenfun_cluster_ll_cpp", (DL_FUNC) &_longscreenfun_cluster_ll_cpp, 3},
    {"_longscreenfun_observed_cluster_ll_cpp", (DL_FUNC) &_longscreenfun_observed_cluster_ll_cpp, 2},
    {"_longscreenfun_missing_cluster_ll_cpp", (DL_FUNC) &_longscreenfun_missing_cluster_ll_cpp, 3},
    {"_longscreenfun_ll_R_cpp", (DL_FUNC) &_longscreenfun_ll_R_cpp, 3},
    {"_longscreenfun_ll_R_cpp_vec", (DL_FUNC) &_longscreenfun_ll_R_cpp_vec, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_longscreenfun(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
